### PR TITLE
Combined separate from datetime import lines

### PR DESCRIPTION
**Pull request by flengyel**
The three ```from datetime import``` lines at the beginning were combined following the scheme

```from X import Y```
```from X import Z```
can be rewritten as
```from X import Y, Z```

### CODE REVIEW

**Comment by woodenzen** [comment]
Since we are practicing and exploring GitHub, I wanted to see about the conversation thread here on GitHub.

I'm not sure where to see the actual changes you propose before I merge. 

Merge done.

**Comment by woodenzen** [comment]
I'm still tiring to get my head around the workflow. I've merged your improvements. Your branch is apparent in the listing. The changes work, of course, but now what? Should I merge your branch into master? Or just let it cook? I want to be a positive maintainer and develop good workflow habits.

**Comment by flengyel** [comment]
You get to decide if and when to merge into the master. Usually contributors will want to see their changes merged into the master. You could have an involved bureaucratic process involving reviewers and parliamentary procedures for advancing branches into the master, but in this case, I would go ahead and merge it. There are cases where it makes sense to let things cook. In this case, it would be to practice letting things cook, but the change is only a line reduction.

**Comment by woodenzen** [comment]
Yes, thank you for this. I'm not wanting to be or seem bureaucratic but instead, I'm trying to learn and be sensitive to the community norms. Now that I've merged your branch to master, do you have to start another branch? 

> Usually contributors will want to see their changes merged into the master. 

Of course! So would I if on the other end of the stick.

**Pull request merged**
